version: "2"
checks:
  method-count:
    config:
      threshold: 50
exclude_patterns:
  - "debian/"
  - "deps/"
  - "scripts/"
  - "wordlists/"
  - "backup/"
  - "docker/"
  - "log/"
  - "tmp/"
  - "images/"
  - "**/__init__.py"
  - "**/*.conf"
  - "**/*.sh"
  - "**/*.qss"
  - "**/*.txt"
  - "**/*.yml"
  - "**/*.md"